version: '3'

services:
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    networks:
     - db_net

  server:
    build: server
    ports:
     - "80:80"
    volumes:
     - ./server:/app
    environment:
     - PORT=80
     - OFFSET=5
    networks:
     - db_net
    links:
     - mongo

  getter:
    build: getter
    environment:
     - GETTER_UPDATE_RATE=600
     - HOURS_INIT=12
    volumes:
     - ./getter:/app
    networks:
     - db_net
    links:
     - mongo

  analyzer:
    build: analyzer
    environment:
     - ANALYZER_UPDATE_RATE=600
     - ANALYZER_BOOTSTRAP_WAIT=120
     - NUM_PROCESSES=8
    volumes:
     - large:/app
    networks:
     - db_net
    links:
     - mongo

networks:
  db_net:

volumes:
  large:
    driver: pure
    driver_opts:
      size: 50G