version: '3'

services:
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    networks:
     - db_net

  server:
    build: server
    ports:
     - "80:80"
    volumes:
     - ./server:/app
    environment:
     - PORT=80
     - OFFSET=5
     - SERVER_UPDATE_RATE=300
     - SERVER_BOOTSTRAP_WAIT=200
    networks:
     - db_net
    links:
     - mongo

  getter:
    build: getter
    environment:
     - GETTER_UPDATE_RATE=600
     - HOURS_INIT=6
    volumes:
     - ./getter:/app
    networks:
     - db_net
    links:
     - mongo

  analyzer:
    build: analyzer
    environment:
     - ANALYZER_UPDATE_RATE=600
     - ANALYZER_BOOTSTRAP_WAIT=100
     - NUM_PROCESSES=8
    volumes:
     - ./analyzer:/app
    networks:
     - db_net
    links:
     - mongo

networks:
  db_net: